FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /usr/bin/frontend frontend/main.go

FROM alpine

LABEL moby.buildkit.frontend.caps="moby.buildkit.frontend.inputs,moby.buildkit.frontend.contexts,moby.buildkit.frontend.subrequests"

COPY --from=builder /usr/bin/frontend /usr/bin/frontend
ENTRYPOINT ["/usr/bin/frontend"]
