FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /usr/bin/analyzer analyzer/main.go
RUN chmod +x /usr/bin/analyzer

FROM alpine

COPY --from=builder /usr/bin/analyzer /usr/bin/analyzer
